#!/usr/bin/env node
/**
 * harmony_caps.js — maintain the HarmonyOS PC target capability profile.
 *
 * Canonical source: references/harmony-pc-capabilities.json (machine-editable).
 * Human-readable view: references/harmony-pc-capabilities.md (RENDERED from the JSON).
 *
 * Two update tiers:
 *   - Tier1 sync()  : auto-check rows that carry a `check {via:'cmd-pkgs'|'pypi', names}`
 *                     against the OpenHarmony PC community sources (reuses
 *                     web/harmony-mirror.js cmd-pkgs/PyPI fetch+cache). A hit ⇒ status
 *                     `available` (+source+checked_at); a miss does NOT downgrade
 *                     (absence in the list ≠ unavailable) — only stamps checked_at.
 *   - Tier3         : human curation via the panel (#/harmony-caps) — server patches a
 *                     row's status/source then re-renders. (Not in this file.)
 *
 * Zero-dependency: Node stdlib + web/harmony-mirror.js. Standalone CLI (offline/CI) too:
 *   node scripts/harmony_caps.js sync     # online: refresh check-rows from community
 *   node scripts/harmony_caps.js render   # offline: regenerate the .md from the JSON
 */
'use strict';

const fs = require('fs');
const path = require('path');
const mirror = require('../web/harmony-mirror');

const CAPS_JSON = path.join(__dirname, '..', 'references', 'harmony-pc-capabilities.json');
const CAPS_MD = path.join(__dirname, '..', 'references', 'harmony-pc-capabilities.md');

const STATUS_MD = { available: '✅ 已支持', partial: '🟡 部分支持', unavailable: '❌ 不支持', unknown: '⬜ 未核实' };

function load() { return JSON.parse(fs.readFileSync(CAPS_JSON, 'utf8')); }
function save(data) { fs.writeFileSync(CAPS_JSON, JSON.stringify(data, null, 2) + '\n'); }

// Render the human-readable .md from the JSON (regenerated by every writer).
function render(data) {
  data = data || load();
  const L = ['# HarmonyOS PC —— 目标平台能力画像（由 harmony-pc-capabilities.json 渲染，勿手改本 .md）', ''];
  if (data.synced_at) L.push(`> 最近联网同步：${data.synced_at}`, '');
  if (data.intro) L.push('> ' + data.intro.replace(/\n/g, '\n> '), '');
  for (const sec of data.sections || []) {
    L.push(`## ${sec.title}`, '', '| 能力 | 状态 | 来源 | 核对时间 | 说明 |', '|------|------|------|----------|------|');
    for (const r of sec.rows || []) {
      const st = STATUS_MD[r.status] || r.status || '';
      const cell = (s) => String(s == null ? '' : s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
      L.push(`| ${cell(r.capability)} | ${st} | ${cell(r.source)} | ${cell(r.checked_at)} | ${cell(r.note)} |`);
    }
    L.push('');
  }
  fs.writeFileSync(CAPS_MD, L.join('\n'));
  return CAPS_MD;
}

// Tier1: refresh every row that carries a `check` against the community sources.
async function sync() {
  const data = load();
  const today = new Date().toISOString().slice(0, 10);
  const refreshed = new Set();   // re-fetch each community source at most once per run
  let checked = 0, flipped = 0;
  for (const sec of data.sections || []) {
    for (const r of sec.rows || []) {
      const chk = r.check;
      if (!chk || !Array.isArray(chk.names) || !chk.names.length) continue;
      checked++;
      const eco = chk.via === 'pypi' ? 'python' : 'cpp';   // 'cmd-pkgs' → cpp list
      let hitName = null;
      for (const nm of chk.names) {
        const refresh = !refreshed.has(eco); refreshed.add(eco);  // force-refresh only the first probe per eco
        try { if (await mirror.isAdapted(eco, nm, refresh)) { hitName = nm; break; } } catch (_) {}
      }
      r.checked_at = today;
      if (hitName) {
        if (r.status !== 'available') flipped++;
        r.status = 'available';
        r.source = `${mirror.MIRROR_LABEL[eco]} — ${hitName}`;
      } else {
        // absence ≠ unavailable; keep prior status, just note we looked.
        r.note = (r.note ? r.note.replace(/（\d{4}-\d\d-\d\d 未在.*?列出）\s*$/, '').trim() : '')
          + `（${today} 未在${chk.via} 列出，不代表不支持）`;
      }
    }
  }
  data.synced_at = new Date().toISOString();
  save(data);
  render(data);
  return { checked, flipped, synced_at: data.synced_at };
}

// Tier3 helper (used by the server): patch one row by id, stamp checked_at, re-render.
function patchRow(id, patch) {
  const data = load();
  let row = null;
  for (const sec of data.sections || []) { const r = (sec.rows || []).find((x) => x.id === id); if (r) { row = r; break; } }
  if (!row) throw new Error(`unknown capability row: ${id}`);
  if (patch.status != null) row.status = patch.status;
  if (patch.source !== undefined) row.source = patch.source;
  if (patch.note !== undefined) row.note = patch.note;
  row.checked_at = new Date().toISOString().slice(0, 10);
  save(data);
  render(data);
  return row;
}

// Tier3 helper (server/panel): create-or-update a row in a section, ADDING the section if absent,
// then re-render. Promotes an unknown/caps_gap target assumption into a curated capability row so a
// later serve-time caps re-projection can bind to it. Distinct from patchRow (which requires the row
// to exist). Returns {section, row, created}.
function upsertRow(payload) {
  const p = payload || {};
  if (!p.sectionId || !p.id) throw new Error('upsertRow requires sectionId and id');
  const data = load();
  data.sections = Array.isArray(data.sections) ? data.sections : [];
  let sec = data.sections.find((s) => s && s.id === p.sectionId);
  if (!sec) { sec = { id: p.sectionId, title: p.sectionTitle || p.sectionId, rows: [] }; data.sections.push(sec); }
  else if (p.sectionTitle && !sec.title) sec.title = p.sectionTitle;
  sec.rows = Array.isArray(sec.rows) ? sec.rows : [];
  let row = sec.rows.find((x) => x && x.id === p.id);
  const created = !row;
  if (!row) { row = { id: p.id, capability: '', status: 'unknown', source: null, checked_at: null, note: '', check: null }; sec.rows.push(row); }
  if (p.capability != null) row.capability = p.capability;
  if (p.status != null) row.status = p.status;
  if (p.source !== undefined) row.source = p.source;
  if (p.note !== undefined) row.note = p.note;
  row.checked_at = new Date().toISOString().slice(0, 10);
  save(data);
  render(data);
  return { section: sec.id, row, created };
}

module.exports = { load, save, render, sync, patchRow, upsertRow, CAPS_JSON, CAPS_MD };

if (require.main === module) {
  const cmd = process.argv[2] || 'render';
  if (cmd === 'render') { console.log('rendered →', render()); }
  else if (cmd === 'sync') { sync().then((s) => console.log('synced:', JSON.stringify(s))).catch((e) => { console.error(e.message); process.exit(1); }); }
  else { console.error('usage: harmony_caps.js sync|render'); process.exit(2); }
}
